StoreApp/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Services.Contracts;

namespace StoreApp.Controllers;

public class OrderController : Controller
{
    private readonly IServiceManager _serviceManager;
    private readonly Cart _cart;

    public OrderController(IServiceManager serviceManager, Cart cart)
    {
        _serviceManager = serviceManager;
        _cart = cart;
    }

    [Authorize]
    public ViewResult Checkout() => View(new Order());

    [HttpPost]
    public IActionResult Checkout([FromForm] Order order)
    {
        if (_cart.Lines.Count == 0)
        {
            ModelState.AddModelError("", "Sorry, your cart is empty.");
        }

        order.Lines = _cart.Lines.ToArray();
        order.OrderedDate = DateTime.Now;
        _serviceManager.OrderService.SaveOrder(order);
        _cart.Clear();
        return RedirectToPage("/Complete", new { OrderId = order.Id });
    }
}

StoreApp/Pages/Cart.cshtml.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.Contracts;
using StoreApp.Infrastructure.Extensions;

namespace StoreApp.Pages;

public class CartModel : PageModel
{
    private IServiceManager _serviceManager;
    public Cart Cart { get; set; }
    public string ReturnUrl { get; set; } = "/";
    public CartModel(IServiceManager serviceManager, Cart cart)
    {
        _serviceManager = serviceManager;
        Cart = cart;
    }

    public void OnGet(string returnUrl)
    {
        ReturnUrl = returnUrl ?? "/";
    }

    public IActionResult OnPost(int id, string returnUrl)
    {
        
        Product product = _serviceManager.ProductService.GetById(id,false);
        if (product is not null)
        {
            Cart.AddLine(product, 1);
        }
        return RedirectToPage(new {returnUrl = returnUrl});
    }

    public void OnPostRemove(int id)
    {
        Product? product = _serviceManager.ProductService.GetById(id, false);
        if (product is not null)
        {
            Cart.RemoveLine(product); 
        }
    }
}

StoreApp/Pages/Complete.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StoreApp.Pages;

public class Complete : PageModel
{
    public void OnGet()
    {
        
    }
}

StoreApp/Pages/Cart.cshtml
@page
@model CartModel

<div>
    <h1 class="text-center">Cart</h1>
    <table >
        <thead>
        <tr>
            <th>Product Name</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>subtotal</th>
            <th></th>

        </tr>
        </thead>
        <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td>@line.Product.ProductName</td>
                <td>@line.Quantity</td>
                <td>@line.Product.Price</td>
                <td>@((line.Product.Price * line.Quantity).ToString("C2"))</td>
                <td>
                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="id" value="@line.Product.Id">
                        <button class="btn btn-danger" type="submit">
                            <i class="fa fa-trash"></i>
                            Remove
                        </button>
                    </form>
                </td>
            </tr>
        }
        </tbody>
        <tfoot>
        <tr>
            <td colspan="3">Total: </td>
            <td>@Model.Cart.ComputeTotalValue().ToString("C2")</td>
        </tr>
        </tfoot>
    </table>
    <div class="text-center">
        <div class="btn-group">
            <a class="btn btn-outline-primary" asp-controller="Order" asp-action="Checkout">Checkout</a>
            <a class="btn btn-primary" href="@Model?.ReturnUrl">Continue Shopping</a>
        </div>
    </div>
</div>

StoreApp/Pages/Complete.cshtml
@page

<div class="text-center">
    <h1>Thanks!</h1>
    <p>Thanks for placing order #@OrderId</p>
    <p>We will deliver your order as soon as possible</p>
    <a asp-action="Index" asp-controller="Home" class="btn btn-primary">Return to Store</a>
</div>


@functions{
    [BindProperty(SupportsGet = true)]
    public string  OrderId { get; set; }
}