StoreApp/Components/CartSummaryViewComponent.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Components;

public class CartSummaryViewComponent : ViewComponent
{
    private readonly Cart _cart;

    public CartSummaryViewComponent(Cart cart)
    {
        _cart = cart;
    }

    public string Invoke()
    {
        
        return _cart.Lines.Sum(l => l.Quantity).ToString();;
    }
}

StoreApp/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Services.Contracts;

namespace StoreApp.Components;

public class ProductSummaryViewComponent : ViewComponent
{
    private readonly IServiceManager _manager;

    public ProductSummaryViewComponent(IServiceManager manager)
    {
        _manager = manager;
    }
    public string Invoke() => _manager.ProductService.GetAllProducts(false).Count().ToString();
    
}

StoreApp/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Controllers;

public class CategoryController : Controller
{
    
    private readonly IServiceManager  _manager;
    public CategoryController(IServiceManager manager)
    {
        _manager = manager;
    }
    
    public IActionResult Index()
    {
        var categories = _manager.CategoryService.GetAllCategories(false).ToList();
        return View("Index",categories);
    }
}

StoreApp/Controllers/ProductController.cs
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;
using StoreApp.Models;


namespace StoreApp.Controllers;

public class ProductController : Controller
{
    private readonly IServiceManager _manager;

    public ProductController(IServiceManager manager)
    {
        _manager = manager;
    }

    public IActionResult Index(ProductRequestParameters parameters)
    {
        var products = _manager.ProductService.GetAllProductsWithDetails(parameters).ToList();
        var pagination = new Pagination()
        {
            CurrentPage = parameters.PageNumber,
            ItemsPerPage = parameters.PageSize,
            TotalItems = _manager.ProductService.GetAllProducts(false).ToList().Count
        };
            
        return View(new ProductListViewModel()
        {
            Products = products,
            Pagination = pagination
        });
    }
    
    
    
    public IActionResult Get([FromRoute(Name = "id")] int id)
    {
        var product = _manager.ProductService.GetById(id,false);
        return View(product);
    }
}

StoreApp/Views/Shared/_Footer.cshtml
<div class="bg-light p-3 border-top">
    <div class="container">
        <div class="row">
            <div class="col-2">
                <div class="text-center">
                    <a asp-action="Index" asp-controller="Home">
                        <i class="fa-solid fa-store fa-3x text-secondary"></i>
                    </a>
                    <p class="text-secondary">Store App</p>
                </div>
            </div>
            <div class="col-8">
                <div class="text-center text-secondary">
                    <p>2023</p>
                    <p>StoreApp ASP.NET Core MVC</p>
                    <div class="btn-group">
                        <a href="#" class="btn btn-secondary">
                            <i class="fa-brands fa-twitter"></i>
                        </a>
                        <a href="#" class="btn btn-secondary">
                            <i class="fa-brands fa-facebook"></i>
                        </a>
                        <a href="#" class="btn btn-secondary">
                            <i class="fa-solid fa-envelope"></i>
                        </a>
                        <a href="#" class="btn btn-secondary">
                            <i class="fa-brands fa-linkedin"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-2">
                <div products="" number="5"></div>
            </div>
        </div>
    </div>
</div>

StoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - StoreApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/StoreApp.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css"/>

</head>
<body class="bg-light">
<header>
    <partial name="_Navbar"/>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer>
    <partial name="_Footer"/>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StoreApp/Views/Shared/_LoginMenu.cshtml
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <li class="nav-item">
        <a target="_blank" class="nav-link text-dark" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Admin</a>
    </li>
}
@if (User.Identity.IsAuthenticated)
{
    <li class="nav-item">
        <a class="nav-link text-dark"
           asp-controller="Account"
           asp-action="LogOut"
           asp-route-returnUrl="@Context.Request.PathAndQuery()"
           >
            <i class="fa fa-x"></i>
            Logout
        </a>
    </li>
}

else
{
    <li class="nav-item">
        <a class="nav-link text-dark"
           asp-controller="Account"
           asp-action="Login"
           asp-route-returnUrl="@Context.Request.PathAndQuery()"
           >
            <i class="fa-solid fa-right-from-bracket"></i>
            Login
        </a>
    </li>
}

StoreApp/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            <i class="fa-solid fa-store fa-2x text-secondary"></i>
        </a>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products(@await Component.InvokeAsync("ProductSummary"))</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-page="/Contact">Contact</a>
                </li>
            </ul>
            
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-page="/Cart">
                        <i class="fa-solid fa-cart-shopping"></i>
                        Cart(@await Component.InvokeAsync("CartSummary"))
                    </a>
                </li>
                <partial name="_LoginMenu" />
            </ul>
        </div>
    </div>
</nav>

StoreApp/Views/Shared/_ProductCard.cshtml
@model Product
<div class="col-md-4 my-4">
    <div class="card" style="width: 18rem">
        <div class="card-header">
            <p class="card-text">@Model.ProductName</p>
        </div>
        <img src="@Model?.ImageUrl" class="card-img-top"/>
        <div class="card-body">
            <div class="text-center text-danger">
                <p>@Model.Price.ToString("C")</p>
            </div>
            <div class="d-flex justify-content-center">
                <div class="btn-group">
                    <form method="post" asp-page="/cart">
                        <input type="hidden" asp-for="Id">
                        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()">
                        <button class="btn btn-outline-secondary" type="submit">
                            <i class="fa fa-cart-plus"></i>
                        </button>
                    </form>
                    
                    <a class="btn btn-outline-secondary mx-1 rounded-2" asp-controller="Product" asp-action="Get" asp-route-id="@Model.Id">
                        <i class="fa-solid fa-arrow-right"></i>
                    </a>
                    
                </div>
            </div>
        </div>
    </div>
</div>