StoreApp/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Services.Contracts;

namespace StoreApp.Components;

public class ProductSummaryViewComponent : ViewComponent
{
    private readonly IServiceManager _manager;

    public ProductSummaryViewComponent(IServiceManager manager)
    {
        _manager = manager;
    }
    public string Invoke() => _manager.ProductService.GetAllProducts(false).Count().ToString();
    
}

StoreApp/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Controllers;

public class CategoryController : Controller
{
    
    private readonly IServiceManager  _manager;
    public CategoryController(IServiceManager manager)
    {
        _manager = manager;
    }
    
    public IActionResult Index()
    {
        var categories = _manager.CategoryService.GetAllCategories(false).ToList();
        return View("Index",categories);
    }
}

StoreApp/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Services.Contracts;

namespace StoreApp.Controllers;

public class OrderController : Controller
{
    private readonly IServiceManager _serviceManager;
    private readonly Cart _cart;

    public OrderController(IServiceManager serviceManager, Cart cart)
    {
        _serviceManager = serviceManager;
        _cart = cart;
    }

    [Authorize]
    public ViewResult Checkout() => View(new Order());

    [HttpPost]
    public IActionResult Checkout([FromForm] Order order)
    {
        if (_cart.Lines.Count == 0)
        {
            ModelState.AddModelError("", "Sorry, your cart is empty.");
        }

        order.Lines = _cart.Lines.ToArray();
        order.OrderedDate = DateTime.Now;
        _serviceManager.OrderService.SaveOrder(order);
        _cart.Clear();
        return RedirectToPage("/Complete", new { OrderId = order.Id });
    }
}

StoreApp/Controllers/ProductController.cs
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;
using StoreApp.Models;


namespace StoreApp.Controllers;

public class ProductController : Controller
{
    private readonly IServiceManager _manager;

    public ProductController(IServiceManager manager)
    {
        _manager = manager;
    }

    public IActionResult Index(ProductRequestParameters parameters)
    {
        var products = _manager.ProductService.GetAllProductsWithDetails(parameters).ToList();
        var pagination = new Pagination()
        {
            CurrentPage = parameters.PageNumber,
            ItemsPerPage = parameters.PageSize,
            TotalItems = _manager.ProductService.GetAllProducts(false).ToList().Count
        };
            
        return View(new ProductListViewModel()
        {
            Products = products,
            Pagination = pagination
        });
    }
    
    
    
    public IActionResult Get([FromRoute(Name = "id")] int id)
    {
        var product = _manager.ProductService.GetById(id,false);
        return View(product);
    }
}

StoreApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/StoreApp.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css"/>
    
</head>
<body>
<header>
    <partial name="_Navbar"/>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StoreApp/Areas/Admin/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand text-white"  asp-controller="Dashboard" asp-action="Index">Admin</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-white" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-controller="Product" asp-action="Index">Products (@await Component.InvokeAsync("ProductSummary"))</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-white" asp-controller="Category" asp-action="Index">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-controller="Order" asp-action="Index">Orders</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-controller="Role" asp-action="Index">Roles</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-controller="User" asp-action="Index">Users</a>
                </li>
            </ul>

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a target="_blank" class="nav-link text-white" asp-area="" asp-action="Index" asp-controller="Home">
                        <i class="fa fa-search"></i>
                        Web
                    </a>
                </li>
                <li class="nav-item">
                    <a 
                        class="nav-link text-white" 
                        asp-area="" 
                        asp-action="Logout" 
                        asp-controller="Account">
                        Logout
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>