StoreApp/Components/CartSummaryViewComponent.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Components;

public class CartSummaryViewComponent : ViewComponent
{
    private readonly Cart _cart;

    public CartSummaryViewComponent(Cart cart)
    {
        _cart = cart;
    }

    public string Invoke()
    {
        
        return _cart.Lines.Sum(l => l.Quantity).ToString();;
    }
}

StoreApp/Components/CategoriesMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Components;

public class CategoriesMenuViewComponent : ViewComponent
{
    private readonly IServiceManager _manager;

    public CategoriesMenuViewComponent(IServiceManager manager)
    {
        _manager = manager;
    }

    public IViewComponentResult Invoke()
    {
        var categories = _manager.CategoryService.GetAllCategories(false).ToList();
        return View(categories);
    }
}

StoreApp/Components/CategoriesSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Components;

public class CategoriesSummaryViewComponent : ViewComponent
{
    private readonly IServiceManager _manager;

    public CategoriesSummaryViewComponent(IServiceManager manager)
    {
        _manager = manager;
    }

    public string Invoke(int id)
    {
        var products = _manager.ProductService.GetAllProducts(false).Where(p => p.CategoryId == id).ToList();
        return products.Count().ToString();
    }
}

StoreApp/Components/ProductFilterMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Components;

public class ProductFilterMenuViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        return View();
    }
}

StoreApp/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Services.Contracts;

namespace StoreApp.Components;

public class ProductSummaryViewComponent : ViewComponent
{
    private readonly IServiceManager _manager;

    public ProductSummaryViewComponent(IServiceManager manager)
    {
        _manager = manager;
    }
    public string Invoke() => _manager.ProductService.GetAllProducts(false).Count().ToString();
    
}

StoreApp/Components/ShowCaseViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Components;

public class ShowCaseViewComponent : ViewComponent
{
    private readonly IServiceManager _manager;

    public ShowCaseViewComponent(IServiceManager manager)
    {
        _manager = manager;
    }

    public IViewComponentResult Invoke()
    {
        var products = _manager.ProductService.GetShowCaseProducts(false);
        return View(products);
    }
}

StoreApp/Views/Shared/Components/CategoriesMenu/Default.cshtml
@model List<Category>
<div>
    <h6 class="text-secondary">
    <i class="fa fa-list"></i>
    Category    
    </h6>
</div>
<div class="text-center my-4">
    <ul class="list-group">
        @foreach (var category in Model)
        {
            <li class="list-group-item">
                <a  asp-action="Index" asp-route-categoryId="@category?.Id">
                    @category.CategoryName (@await Component.InvokeAsync("CategoriesSummary", category.Id))
                </a>
            </li>
        }
        <li class="list-group-item">
            <a asp-action="Index" asp-route-categoryId="">
                All(@Model.Count)
            </a>
        </li>
        
    </ul>
</div>